CREATE TABLE PASSENGER (
  ID         NUMBER PRIMARY KEY,
  LAST_NAME             VARCHAR(50) NOT NULL,
  NATIONALITY           VARCHAR(50) NOT NULL,
  DATE_OF_BIRTH         DATE NOT NULL,
  PASSPORT_CODE         VARCHAR(50) NOT NULL
)
