CREATE TABLE FLIGHT (
  ID         NUMBER PRIMARY KEY,
  DATE_FLIGHT     DATE NOT NULL,
  CITY_FROM       VARCHAR(50) NOT NULL,
  CITY_TO          VARCHAR(50) NOT NULL,
  ID_PLANE NUMBER,
  FOREIGN KEY(ID_PLANE) REFERENCES PLANE(ID)
)

